module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 20000,
  PLAYER_SPEED: 200,
  PLAYER_FIRE_COOLDOWN: 0.1,

  BULLET_RADIUS: 3,

  // ZOMBIE_RADIUS: 20,
  ZOMBIE_EASY_MAX_AMOUNT: 250,
  ZOMBIE_NORMAL_MAX_AMOUNT: 175,
  ZOMBIE_HARD_MAX_AMOUNT: 125,

  ZOMBIE_BOSS_RADIUS: 50,
  ZOMBIE_BOSS_EASY_MAX_AMOUNT: 10,
  ZOMBIE_BOSS_NORMAL_MAX_AMOUNT: 5,
  ZOMBIE_BOSS_HARD_MAX_AMOUNT: 3,
  ZOMBIE_BOSS_LEGEND_MAX_AMOUNT: 1,

  SCORE_BULLET_HIT: 5,

  THING_AMOUNT: 500,
  THING_RADIUS: 15,

  MAP_SIZE: 10000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    ROTATE: 'rotate',
    CLICK: 'click',
    LEVEL_UP: 'levelup',
    UPDATE_WEAPON: 'update_weapon',
    ADD_NEW_SKILL: 'new_skill',
    USE_ACTIVE_SKILL: 'active_skill',
    GAME_OVER: 'dead',
    SAVE_ID_PLAYER: 'save_id_player'
  },
});
